### ISSUE TITLE
项目维护咨询

### ISSUE THREAD

**Issue by lifesign** [void-main/UnofficialDocs#3]
你好 请问这个项目还在维护么，目前看距离官方差了有一半的 commit ，还有不少没有翻译的内容

**Comment by void-main** [comment]
Hi @lifesign 感谢你对这个项目有兴趣！目前由于个人精力有限，确实不再维护了。如果感兴趣的话你可以fork这个项目，然后发pull request～

**Comment by TobyYoung0412** [comment]
请问是否有计划翻译sublime 官方文档？还是已经有官方文档的中文版了？
@lifesign @void-main

**Comment by howiezhao** [comment]
@stdAri 网上存在许多 Sublime Text 3 官方文档的中文翻译版，由于个人没看过，所以不确保翻译质量如何，此外，Sublime Text 3 官方文档的第一段话就这样写到：
> The Sublime Text Unofficial Documentation is an excellent supplementary resource, with a huge amount of information not covered in the official documentation.
